package br.jus.trt4.processo.domain;

import br.jus.trt4.processo.exception.RegraDeNegocioException;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

// -----------------------------------------------------------------------------------------------
// Todos os imports acima começam com "javax.persistence.*" — a especificação JPA (Jakarta EE 8),
// NÃO o Hibernate. Hibernate é quem vai LER essas anotações em runtime e gerar o SQL de fato.
// Ver docs/05-especificacao-vs-implementacao.md para a explicação completa dessa separação.
// -----------------------------------------------------------------------------------------------

/**
 * Agregado raiz do domínio: um Processo Judicial. "Agregado raiz" aqui tem o mesmo sentido que
 * você já usa em DDD no .NET — é o único ponto de entrada para mutação consistente do conjunto
 * {@code Processo -> Partes/Movimentações}; ninguém deveria pegar uma {@link Movimentacao} solta
 * e vinculá-la a um processo por fora, sempre via {@link #adicionarMovimentacao}.
 */
// -------------------------------------------------------------------------------------------
// @Entity — marca esta classe como uma entidade gerenciada pelo JPA/Hibernate: cada instância
// vira (potencialmente) uma linha na tabela mapeada. É a anotação que ativa TODO o resto (sem
// ela, @Id, @Column etc. seriam apenas metadados inertes, ignorados).
// Paralelo .NET/EF Core: registrar a classe como um DbSet<Processo> no seu DbContext — a
// diferença é que, no EF Core, "ser uma entidade" é uma decisão tomada NO DbContext (fora da
// classe); no JPA, a classe se autodeclara entidade via annotation, independente de quem a usa.
// -------------------------------------------------------------------------------------------
@Entity
// -------------------------------------------------------------------------------------------
// @Table(name = "processo") — nome exato da tabela no banco. Poderíamos omitir esta annotation:
// sem ela, o Hibernate INFERE o nome da tabela a partir do nome da classe, aplicando a
// "physical naming strategy" padrão do Spring Boot (que converte CamelCase para snake_case) —
// "Processo" viraria "processo" de qualquer jeito. Declaramos explicitamente aqui só para deixar
// o mapeamento óbvio para quem está lendo, sem precisar saber a regra de conversão implícita.
// Paralelo .NET/EF Core: equivalente ao atributo [Table("processo")] ou a
// `modelBuilder.Entity<Processo>().ToTable("processo")` na Fluent API.
// -------------------------------------------------------------------------------------------
@Table(name = "processo")
public class Processo {

    // ---------------------------------------------------------------------------------------
    // @Id — marca este campo como chave primária. Toda @Entity precisa de exatamente um (ou uma
    // combinação, para chave composta) campo marcado assim. Paralelo EF Core: convenção de nome
    // "Id" já é reconhecida automaticamente OU [Key] explícito — aqui a marcação é sempre
    // explícita, nunca por convenção de nome.
    //
    // @GeneratedValue(strategy = GenerationType.IDENTITY) — delega a geração do valor da PK para
    // o PRÓPRIO BANCO (uma coluna auto-incremento/identity nativa), em vez do Hibernate gerar o
    // valor sozinho antes do INSERT (outras estratégias: SEQUENCE, TABLE, AUTO). IDENTITY é a
    // escolha certa aqui porque nossa migration Flyway (V1__criar_tabelas_processo.sql) declara
    // as colunas com "GENERATED BY DEFAULT AS IDENTITY" — os dois lados (SQL e anotação Java)
    // precisam concordar sobre quem gera o valor.
    // Paralelo EF Core: equivalente a uma coluna configurada com
    // `.ValueGeneratedOnAdd()`/identity column do SQL Server — mesmíssima ideia.
    // ---------------------------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ---------------------------------------------------------------------------------------
    // @Column — configura detalhes da coluna mapeada (nome, obrigatoriedade, tamanho, unicidade).
    // Sem @Column, o campo ainda seria mapeado (toda propriedade não-transiente de uma @Entity é
    // uma coluna, por padrão) — usamos aqui só para refinar as regras.
    // Paralelo EF Core: mistura de [Column]/[Required]/[MaxLength] (DataAnnotations) ou da
    // Fluent API `.HasMaxLength()`/`.IsRequired()`/`.HasIndex().IsUnique()`.
    //
    // IMPORTANTE: nullable=false e unique=true aqui SÓ afetam o DDL gerado se deixássemos o
    // Hibernate criar o schema (ddl-auto=update/create). Como usamos ddl-auto=validate (Flyway
    // manda no schema, ver application.yml), essas flags aqui servem de DOCUMENTAÇÃO da regra —
    // quem efetivamente CRIA a constraint UNIQUE é o SQL da migration. Mantê-los sincronizados é
    // responsabilidade de quem edita a entidade.
    // ---------------------------------------------------------------------------------------
    @Column(name = "numero", nullable = false, unique = true, length = 30)
    private String numero;

    @Column(name = "classe_judicial", length = 150)
    private String classeJudicial;

    @Column(name = "vara", length = 150)
    private String vara;

    // ---------------------------------------------------------------------------------------
    // @Enumerated(EnumType.STRING) — diz ao Hibernate para persistir o enum como TEXTO (o nome
    // da constante: "ATIVO", "ARQUIVADO"...), não como o número ordinal (0, 1, 2...), que é o
    // padrão se você OMITIR esta anotação (EnumType.ORDINAL implícito).
    //
    // Isso é uma pegadinha clássica: com ORDINAL, se alguém reordenar as constantes do enum
    // StatusProcesso no futuro (ou inserir uma no meio), os dados JÁ GRAVADOS no banco passam a
    // significar outra coisa silenciosamente — nenhum erro de compilação ou runtime avisa. STRING
    // é mais verboso (ocupa mais espaço) mas é imune a esse problema — é a escolha recomendada
    // em praticamente todo lugar, e vale saber o "porquê" para a prova.
    //
    // Paralelo .NET/EF Core: por padrão, o EF Core converte enums para INT no banco (mais
    // parecido com o ORDINAL do JPA) — para gravar como string, você precisa configurar
    // explicitamente `.HasConversion<string>()` na Fluent API. Ou seja: os defaults são
    // INVERTIDOS entre os dois frameworks — vale prestar atenção.
    // ---------------------------------------------------------------------------------------
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private StatusProcesso status;

    @Column(name = "data_autuacao", nullable = false)
    private LocalDate dataAutuacao;

    // ---------------------------------------------------------------------------------------
    // @OneToMany(mappedBy = "processo", ...) — lado "um" do relacionamento 1:N com Parte.
    //
    // mappedBy = "processo" diz: "quem realmente DONO da chave estrangeira é o campo `processo`
    // lá na classe Parte (anotado com @ManyToOne/@JoinColumn) — eu (Processo) só enxergo a
    // coleção, não crio nenhuma coluna nova aqui". Sem mappedBy, o JPA assumiria um relacionamento
    // bidirecional "duplicado" e tentaria criar uma tabela de junção desnecessária.
    //
    // cascade = CascadeType.ALL: qualquer operação feita no Processo (persistir, remover) se
    // propaga para as Partes associadas — se eu deletar o processo, deleto as partes junto.
    // orphanRemoval = true: se eu REMOVER uma Parte desta lista (sem deletar o processo inteiro),
    // o Hibernate entende que ela virou "órfã" e a apaga do banco também.
    //
    // Juntas, essas duas flags implementam o conceito de "agregado" do DDD dentro do JPA: Parte e
    // Movimentacao só existem enquanto penduradas em um Processo — não fazem sentido sozinhas.
    //
    // Paralelo EF Core: `.HasMany(p => p.Partes).WithOne(pa => pa.Processo)` +
    // `.OnDelete(DeleteBehavior.Cascade)` para o cascade; orphanRemoval não tem um equivalente de
    // nome idêntico no EF Core, mas o comportamento mais próximo é habilitado automaticamente
    // quando a relação é configurada como obrigatória (a FK é NOT NULL) — o EF Core deleta a
    // entidade filha ao invés de deixá-la com FK nula, já que a FK não permite nulo.
    // ---------------------------------------------------------------------------------------
    @OneToMany(mappedBy = "processo", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Parte> partes = new ArrayList<>();

    @OneToMany(mappedBy = "processo", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Movimentacao> movimentacoes = new ArrayList<>();

    // ---------------------------------------------------------------------------------------
    // Construtor protegido sem argumentos — EXIGÊNCIA da especificação JPA, não frescura nossa.
    // O Hibernate precisa conseguir instanciar a entidade via reflection (sem passar por nenhum
    // construtor "de negócio") para popular os campos depois, ao reidratar uma linha do banco.
    // "protected" (em vez de "public") é uma boa prática: impede código de aplicação de criar um
    // Processo "vazio" por acidente, mas ainda satisfaz o Hibernate, que ignora modificadores de
    // acesso via reflection.
    //
    // Paralelo C#/EF Core: EF Core tem a MESMA exigência (precisa de um construtor sem parâmetros
    // ou de um construtor cujos parâmetros batem com nomes de propriedades) — a diferença é que
    // no C# isso passa despercebido com mais frequência porque o compilador gera um construtor
    // público sem argumentos por padrão quando você não declara nenhum outro; em Java, se você
    // declarar QUALQUER construtor com argumentos (como o de baixo), o construtor padrão deixa de
    // existir automaticamente — você precisa escrevê-lo à mão, como fizemos aqui.
    // ---------------------------------------------------------------------------------------
    protected Processo() {
    }

    /**
     * Construtor "de negócio" — o único jeito público de criar um Processo válido. Um processo
     * sempre nasce com status ATIVO; não existe um "new Processo()" fora do domínio que deixe o
     * status nulo ou inconsistente.
     */
    public Processo(String numero, String classeJudicial, String vara, LocalDate dataAutuacao) {
        this.numero = numero;
        this.classeJudicial = classeJudicial;
        this.vara = vara;
        this.dataAutuacao = dataAutuacao;
        this.status = StatusProcesso.ATIVO;
    }

    /**
     * Vincula uma Parte a este processo. Método de domínio (não um setter de lista) — quem chama
     * não manipula a lista diretamente, evitando um Processo com Partes "penduradas" sem o
     * back-reference correto (ver {@link Parte#vincularProcesso}).
     */
    public void adicionarParte(Parte parte) {
        parte.vincularProcesso(this);
        this.partes.add(parte);
    }

    /**
     * Adiciona uma movimentação ao histórico do processo — COM a regra de negócio central deste
     * módulo: processo arquivado não recebe movimentação nova. Isso é o "modelo rico" que você já
     * pratica em DDD: a invariante mora DENTRO da entidade, não espalhada num service que poderia
     * esquecer de checar.
     */
    public void adicionarMovimentacao(Movimentacao movimentacao) {
        if (this.status == StatusProcesso.ARQUIVADO) {
            throw new RegraDeNegocioException(
                    "Não é possível adicionar movimentação ao processo " + this.numero
                            + ": processo arquivado.");
        }
        movimentacao.vincularProcesso(this);
        this.movimentacoes.add(movimentacao);
    }

    /** Arquiva o processo — a partir daqui, {@link #adicionarMovimentacao} passa a recusar. */
    public void arquivar() {
        this.status = StatusProcesso.ARQUIVADO;
    }

    // ---------------------------------------------------------------------------------------
    // Getters, sem setters públicos para "status" e para as listas — mutação de estado só
    // acontece via os métodos de domínio acima (adicionarParte/adicionarMovimentacao/arquivar).
    // Collections.unmodifiableList evita que quem chamar getMovimentacoes() faça
    // `getMovimentacoes().add(x)` por fora da regra de negócio — a lista devolvida é só leitura.
    // ---------------------------------------------------------------------------------------
    public Long getId() {
        return id;
    }

    public String getNumero() {
        return numero;
    }

    public String getClasseJudicial() {
        return classeJudicial;
    }

    public String getVara() {
        return vara;
    }

    public StatusProcesso getStatus() {
        return status;
    }

    public LocalDate getDataAutuacao() {
        return dataAutuacao;
    }

    public List<Parte> getPartes() {
        return Collections.unmodifiableList(partes);
    }

    public List<Movimentacao> getMovimentacoes() {
        return Collections.unmodifiableList(movimentacoes);
    }

    // ---------------------------------------------------------------------------------------
    // equals/hashCode baseados no "numero" (chave de negócio), não no "id" técnico e NUNCA
    // usando os campos de coleção (partes/movimentacoes teriam que carregar do banco — lazy
    // loading — só para calcular um hashCode, e coleções mutáveis quebram o contrato de
    // hashCode estável exigido por HashSet/HashMap).
    //
    // Pegadinha clássica de JPA/Hibernate (vale MUITO para a prova, ver docs/09): usar o campo
    // "id" no equals/hashCode antes de a entidade ser persistida (quando id ainda é null) faz
    // toda entidade nova parecer "igual" a qualquer outra entidade nova dentro de um
    // HashSet/HashMap — e comparar uma entidade gerenciada (proxy do Hibernate) com
    // "instanceof" em vez de "getClass() != o.getClass()" evita quebrar ao comparar um proxy
    // lazy-loaded com a entidade real. Usar uma chave de NEGÓCIO estável (como "numero", que
    // existe desde a criação do objeto) evita os dois problemas de uma vez.
    // ---------------------------------------------------------------------------------------
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Processo)) {
            return false;
        }
        Processo processo = (Processo) o;
        return Objects.equals(numero, processo.numero);
    }

    @Override
    public int hashCode() {
        return Objects.hash(numero);
    }
}
