-- =================================================================================================
-- V1__criar_tabelas_processo.sql
-- =================================================================================================
-- Convenção de nome exigida pelo Flyway: "V<versao>__<descricao>.sql" (dois underscores entre a
-- versão e a descrição). O Flyway lê essa versão do NOME DO ARQUIVO (não do conteúdo), guarda em
-- uma tabela de controle própria ("flyway_schema_history", criada automaticamente) e garante que
-- cada arquivo só roda UMA VEZ por banco, na ordem numérica. Rodar de novo um V1 já aplicado, ou
-- editar um arquivo já aplicado, quebra a validação do Flyway de propósito (ele guarda um
-- checksum) — a única forma de "corrigir" um V1 já rodado é criar um V2 que altera o que for
-- preciso, nunca editar o V1 retroativamente.
--
-- Paralelo .NET: bem diferente do EF Core Migrations, onde CADA migration é uma CLASSE C# gerada
-- a partir do diff entre o modelo atual e o snapshot anterior (`dotnet ef migrations add`) — aqui
-- é SQL puro, escrito à mão, e é você quem decide o que cada versão faz. Filosofia "SQL-first"
-- (você pensa em schema) vs "code-first" (você pensa em classes e o schema é derivado).
--
-- Sintaxe "GENERATED BY DEFAULT AS IDENTITY": escolhida deliberadamente por ser PADRÃO SQL (SQL:2003),
-- suportada tanto pelo H2 (usado em dev/testes) quanto pelo PostgreSQL 10+ (usado em produção,
-- Fase 8) SEM MUDAR UMA LINHA deste script. Evitamos "SERIAL" (sintaxe proprietária do
-- PostgreSQL, não existe no H2/Oracle/SQL Server) e "AUTO_INCREMENT" (sintaxe do MySQL) de
-- propósito — ver docs/09-notas-para-prova.md.
-- =================================================================================================

-- Agregado raiz: Processo Judicial.
CREATE TABLE processo (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          VARCHAR(30)  NOT NULL,
    classe_judicial VARCHAR(150),
    vara            VARCHAR(150),
    -- Guardado como texto (ver @Enumerated(EnumType.STRING) em Processo.java), nao como numero.
    status          VARCHAR(20)  NOT NULL,
    data_autuacao   DATE         NOT NULL,
    CONSTRAINT uk_processo_numero UNIQUE (numero)
);

-- Entidade filha: Parte (autor/reu) vinculada a um processo.
CREATE TABLE parte (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    tipo_parte  VARCHAR(20)  NOT NULL,
    documento   VARCHAR(20)  NOT NULL,
    processo_id BIGINT       NOT NULL,
    CONSTRAINT fk_parte_processo FOREIGN KEY (processo_id) REFERENCES processo (id)
);

-- Entidade filha: Movimentacao (historico) vinculada a um processo.
CREATE TABLE movimentacao (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao         VARCHAR(500)  NOT NULL,
    tipo_movimentacao VARCHAR(20)   NOT NULL,
    data_movimentacao TIMESTAMP     NOT NULL,
    processo_id       BIGINT        NOT NULL,
    CONSTRAINT fk_movimentacao_processo FOREIGN KEY (processo_id) REFERENCES processo (id)
);

-- Indices nas FKs: toda consulta "movimentacoes/partes de UM processo" (o caso de uso mais comum
-- deste modulo, via findByProcessoId) filtra por essas colunas — sem indice, o banco faria table
-- scan a cada chamada conforme os dados crescessem.
CREATE INDEX idx_parte_processo ON parte (processo_id);
CREATE INDEX idx_movimentacao_processo ON movimentacao (processo_id);
